# coding=utf-8
"""Helpers for publishing generated HTML reports to S3-compatible storage."""

from __future__ import annotations

import atexit
import os
from pathlib import Path
from typing import Optional


_ATEXIT_UPLOAD_REGISTERED = False


def _get_r2_client_and_bucket():
    """Create an S3-compatible client from environment variables."""
    bucket_name = os.environ.get("S3_BUCKET_NAME", "").strip()
    access_key_id = os.environ.get("S3_ACCESS_KEY_ID", "").strip()
    secret_access_key = os.environ.get("S3_SECRET_ACCESS_KEY", "").strip()
    endpoint_url = os.environ.get("S3_ENDPOINT_URL", "").strip()
    region = os.environ.get("S3_REGION", "").strip() or "auto"

    if not all([bucket_name, access_key_id, secret_access_key, endpoint_url]):
        return None, None

    import boto3
    from botocore.config import Config

    client = boto3.client(
        "s3",
        endpoint_url=endpoint_url,
        aws_access_key_id=access_key_id,
        aws_secret_access_key=secret_access_key,
        region_name=region,
        config=Config(signature_version="s3v4"),
    )
    return client, bucket_name


def _put_html_file(client, bucket_name: str, local_path: Path, key: str) -> bool:
    """Upload one HTML file to R2/S3."""
    try:
        body = local_path.read_bytes()
        client.put_object(
            Bucket=bucket_name,
            Key=key,
            Body=body,
            ContentLength=len(body),
            ContentType="text/html; charset=utf-8",
            CacheControl="no-cache" if key == "reports/latest.html" else "public, max-age=31536000",
        )
        print(f"[R2] 已上传完整报告: {key}")
        return True
    except Exception as e:
        print(f"[R2] 上传完整报告失败 {key}: {e}")
        return False


def upload_generated_html_reports() -> None:
    """Upload HTML files generated by the main report writer.

    The main program writes HTML directly to output/html/*. This function scans
    those generated files at process exit and publishes them to R2.
    """
    public_base_url = os.environ.get("R2_PUBLIC_BASE_URL", "").strip().rstrip("/")
    if not public_base_url:
        return

    latest_local = Path("output/html/latest/current.html")
    html_root = Path("output/html")

    if not latest_local.exists() and not html_root.exists():
        return

    try:
        client, bucket_name = _get_r2_client_and_bucket()
        if client is None or not bucket_name:
            print("[R2] 远程存储环境变量不完整，跳过 HTML 报告上传")
            return

        uploaded_any = False

        # Stable latest link used by email/bookmarks.
        if latest_local.exists():
            uploaded_any = _put_html_file(client, bucket_name, latest_local, "reports/latest.html") or uploaded_any

        # Historical latest dated file, e.g. output/html/2026-04-27/14-10.html.
        dated_files = [
            p for p in html_root.glob("20??-??-??/*.html")
            if p.is_file()
        ] if html_root.exists() else []
        if dated_files:
            newest = max(dated_files, key=lambda p: p.stat().st_mtime)
            date_folder = newest.parent.name
            history_key = f"reports/{date_folder}/{newest.name}"
            uploaded_any = _put_html_file(client, bucket_name, newest, history_key) or uploaded_any

        if uploaded_any:
            print(f"[R2] 完整报告链接: {public_base_url}/reports/latest.html")
    except Exception as e:
        print(f"[R2] HTML 报告上传流程失败: {e}")


def _register_atexit_upload() -> None:
    """Register an exit hook so direct local HTML writes still get uploaded."""
    global _ATEXIT_UPLOAD_REGISTERED
    if _ATEXIT_UPLOAD_REGISTERED:
        return
    atexit.register(upload_generated_html_reports)
    _ATEXIT_UPLOAD_REGISTERED = True


def enable_remote_html_upload() -> None:
    """Enable HTML report publishing for both storage and direct local writes."""
    _register_atexit_upload()

    try:
        from trendradar.storage.remote import RemoteStorageBackend
    except Exception:
        return

    if getattr(RemoteStorageBackend, "_html_upload_enabled", False):
        return

    original = getattr(RemoteStorageBackend, "save_html_report", None)
    if not original:
        return

    def save_html_report(self, html_content: str, filename: str) -> Optional[str]:
        local_path = original(self, html_content, filename)
        if not local_path:
            return local_path

        public_base_url = os.environ.get("R2_PUBLIC_BASE_URL", "").strip().rstrip("/")
        if not public_base_url:
            print("[远程存储] 未配置 R2_PUBLIC_BASE_URL，HTML 报告仅保存到临时目录")
            return local_path

        try:
            body = html_content.encode("utf-8")
            date_folder = self._format_date_folder()
            history_key = f"reports/{date_folder}/{Path(filename).name}"
            latest_key = "reports/latest.html"

            for key in (history_key, latest_key):
                self.s3_client.put_object(
                    Bucket=self.bucket_name,
                    Key=key,
                    Body=body,
                    ContentLength=len(body),
                    ContentType="text/html; charset=utf-8",
                    CacheControl="no-cache" if key == latest_key else "public, max-age=31536000",
                )
                print(f"[远程存储] HTML 报告已上传: {key}")

            latest_url = f"{public_base_url}/{latest_key}"
            history_url = f"{public_base_url}/{history_key}"
            print(f"[远程存储] 最新 HTML 报告链接: {latest_url}")
            print(f"[远程存储] 历史 HTML 报告链接: {history_url}")
            return latest_url
        except Exception as e:
            print(f"[远程存储] 上传 HTML 报告到 R2 失败: {e}")
            return local_path

    RemoteStorageBackend.save_html_report = save_html_report
    RemoteStorageBackend._html_upload_enabled = True
